# Generated by Django 3.0.2 on 2020-01-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('company_name', models.CharField(max_length=50)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
