# Generated by Django 3.0.2 on 2020-01-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
